const BEGIN_API_CALL = 'BEGIN_API_CALL'
const END_API_CALL = 'END_API_CALL'
const API_ERROR = 'API_ERROR'
const CLEAR_API_ERROR = 'CLEAR_API_ERROR'


module.exports = {
	BEGIN_API_CALL,
	END_API_CALL,
	API_ERROR,
	CLEAR_API_ERROR
}
